baseURL = '/'
languageCode = 'en-us'
title = 'Sailing Sweet Aria'
theme = 'hugo-resume'

[params]
profileImage = "img/circleshot.jpg"
address = "White Stone, VA"
email = "morgan@sailingsweetaria.com"
firstName = "Sailing"
lastName = "Sweet Aria"
phone = "1-555-555-1234"
showContact = true

[[params.handles]]
link = "https://www.linkedin.com/in/edwardwebb/"
name = "Instagram"

